import type { Metadata } from "next";
import { Special_Gothic_Expanded_One, TASA_Orbiter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const specialGothicExpandedOne = Special_Gothic_Expanded_One({
    variable: "--font-special-gothic-expanded-one",
    subsets: ["latin"],
    weight: ["400"],
    display: "swap",
});

const tasaOrbiter = TASA_Orbiter({
    variable: "--font-tasa-orbiter",
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="ja"
            className={`${specialGothicExpandedOne.variable} ${tasaOrbiter.variable}`}
        >
            <body className="font-sans min-h-screen bg-background text-foreground antialiased">
                <main>{children}</main>
                <Toaster richColors position="top-right" />
            </body>
        </html>
    );
}
